### ISSUE TITLE
Unable to implement bot

### ISSUE THREAD

**Issue by sniper365** [oxtx/CryptoTrader#1]
Hey @hstead1104 
Just wondering if you can implement successfully? 
I got the some issues. (honestly it's some kinda hard-coded;). Just wonder you are working on Freelancer or job board like indeed, wellfound, linkedin. Let me know. It seems you started working

**Comment by oxtx** [comment]
Right. It is hard-corded. I can help you if you wanna implement it. And task to only stand.

**Comment by sniper365** [comment]
So you have project you are working on? I am job-free. let's collaborate :)
